# Generated by Django 6.0.3 on 2026-03-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativeConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('tentatives', models.PositiveIntegerField(default=0)),
                ('bloque_jusqu', models.DateTimeField(blank=True, null=True)),
                ('derniere_tentative', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tentative de connexion',
                'unique_together': {('username', 'adresse_ip')},
            },
        ),
    ]
