# Generated by Django 6.0.3 on 2026-03-29 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=20, unique=True)),
                ('type_compte', models.CharField(choices=[('courant', 'Compte Courant'), ('epargne', 'Compte Épargne')], default='courant', max_length=10)),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte',
            },
        ),
    ]
