# Generated by Django 6.0.1 on 2026-04-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='plafond_virement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour aucune limite.', max_digits=12, null=True, verbose_name='Plafond journalier de virement (FCFA)'),
        ),
    ]
