# Generated by Django 6.0.3 on 2026-03-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('virement', 'Virement'), ('depot', 'Dépôt'), ('retrait', 'Retrait')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.BooleanField(default=True)),
                ('compte_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_recues', to='comptes.compte')),
                ('compte_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_emises', to='comptes.compte')),
            ],
            options={
                'verbose_name': 'Transaction',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
