# Generated by Django 6.0.1 on 2026-04-02 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_compte_plafond_virement'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='annule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VirementRecurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('frequence', models.CharField(choices=[('quotidien', 'Quotidien'), ('hebdo', 'Hebdomadaire'), ('mensuel', 'Mensuel')], default='mensuel', max_length=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text='Laisser vide pour sans fin', null=True)),
                ('prochaine_execution', models.DateField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('pause', 'En pause'), ('termine', 'Terminé')], default='actif', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virements_recurrents_dest', to='comptes.compte')),
                ('compte_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virements_recurrents_source', to='comptes.compte')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Virement récurrent',
                'ordering': ['prochaine_execution'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='virement_recurrent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_generees', to='transactions.virementrecurrent'),
        ),
    ]
